### ISSUE TITLE
Feature request: provide a Coq OPAM package

### ISSUE THREAD

**Issue by brabalan** [plclub/metalib#17]
Would it be possible to provide metalib as a Coq OPAM package?

**Comment by brabalan** [comment]
Thanks! Do you know when it will be published?

**Comment by liyishuai** [comment]
I can open a PR to coq-extra-dev if needed. Before that you can use: `opam pin --dev-repo add coq-metalib .`

**Comment by liyishuai** [comment]
Proposed to coq-extra-dev: coq/opam-coq-archive#582
