### ISSUE TITLE
[request]coq 8.10 support

### ISSUE THREAD

**Issue by juda** [plclub/metalib#23]
Dear maintainers,

I update my ocaml version to 4.08 and coq version to 8.10, then I re-compile the metalib, getting the error too many times: 

    File "./Metatheory.v", line XXX, characters 0-200:
    Warning: Adding and removing hints in the core database implicitly is
    deprecated. Please specify a hint database.
    [implicit-core-hint-db,deprecated] 

I think it might be that coqc isn't backward compatible. Could you please add new version of coq support?

**Comment by sweirich** [comment]
I have updated the files to remove the warnings with Coq 8.10.2 and ocaml 4.09.0.  Haven't tested yet with prior versions of Coq.

Fixed by c716013d14f04b399f53afc34723ab7bcb4439cc
