### ISSUE TITLE
8.5 changes break 8.4 and there is no tag made

### ISSUE THREAD

**Issue by roachspray** [plclub/metalib#3]
Firs: thank you for the code and having it public :-) 👍  

I know this is minor since most are tracking Coq closely, but I suggest possibly tagging the tree next time you update to mold to new Coq versions for those who are still using <8.5

Thank you again!!

**Comment by sweirich** [comment]
Sorry!  This code hasn't been touched in 3 years --- thought it was safe to modify.  I've added a tag for the version just before my edits.
